---

- name: Playbook import

  hosts: all

  become: yes

  vars:

    mytext: "Hello"



  tasks:

   - name: Ping test
     ping:

   - name: Include test
     include: mkdir.yml
   - name: import test
     include: create_file.yml mytext="Hi!"

