---

- name: install apache and upload web page

  hosts: all

  become: yes



  vars:

   source_folder: ./MyWebSite/

   dest_file: /var/www/html



  tasks:
  - name: Check OS and packet manager
    debug:
     var:  ansible_pkg_mgr
  - debug:
     var: ansible_distribution


  - block: #========Block for RedHat==========

     - name: Install apache web server on RedHat
       yum: name=httpd



     - name: start webserver and make it enable on boot ON REDHAT
       service: name=httpd state=started enabled=yes
    when: ansible_pkg_mgr == "yum"



  - block: #=============Block for Debian==========

     - name: Install apache web server on Debian
       apt: name=apache2


     - name: Start webserver and make it enable on boot ON DEBIAN
       service: name=apache2 state=started enabled=yes
    when: ansible_pkg_mgr == "apt"

  - name: Generate index.html file

    template: src={{ source_folder }}/index.j2 dest={{ dest_file }}/index.html mode=0555

    notify:

     - Restart Apache RedHat

     - Restart Apache Debian

#================================================copy folder======================
  - name: copy myhomepage to server
# copy: src={{ source_folder }}/{{ item }}  dest={{ dest_file}} mode=0555
    copy: src={{ item }}  dest={{ dest_file}} mode=0555
    with_fileglob: "{{source_folder}}/*.*"
#    loop:
 #     - "babek"
  #    - "index.html"
   #   - "her"
    #  - "zero"
    notify:
       -  Restart Apache RedHat
       -  Restart Apache Debian


  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_pkg_mgr == "yum"

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_pkg_mgr != "yum"
